name: Build
on: [ pull_request, push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Grant execute permission for all runners
        run: chmod +x gradlew
      - name: build
        run: ./gradlew build
      
      # Upload part
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install NPM package
        run: npm install @actions/artifact
      - uses: actions/github-script@v7
        name: Artifact script
        with:
          script: |
            const {default: artifact} = require('@actions/artifact')
            const fs = require('fs');

            function getContentFrom(path, check) {
              return fs.readdirSync(path).filter(function (file) {
                return check == fs.statSync(path+'/'+file).isDirectory();
              });
            }

            function getDirectories(path) { return getContentFrom(path, true); }

            function getFiles(path) { return getContentFrom(path, false); }

            for(let fabricVersion of getDirectories("./")) {
              if(!fabricVersion.startsWith("fabric"))
                 continue;
              console.log("Checking for version", fabricVersion);
              let visual = "";
              for(let char of fabricVersion.replace("fabric", "")) {
                if(visual.length > 0 && visual.length % 2 == 0) {
                  visual += ".";
                }
                visual += char;
              }
              let filesDir = "./" + fabricVersion + "/build/libs";
              let files = [];
              for(let build of getFiles(filesDir)) {
                if(!build.endsWith("-sources.jar")) {
                  files.push(filesDir + "/" + build);
                }
              }
              console.log("Uploading version", "1." + visual, "and files", files);
              await artifact.uploadArtifact(
                "NegativityFabric 1." + visual,
                files,
                filesDir,
                { continueOnError: false }
              )
            }
