name: Build
on: [ pull_request, push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'
      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Grant execute permission for all runners
        run: chmod +x gradlew
      - name: build
        run: ./gradlew build
      # this part will change
      - uses: actions/upload-artifact@v3
        with:
          name: NegativityFabric-1.19
          path: fabric19/build/libs/NegativityFabric-19-1.0.0.jar
      - uses: actions/upload-artifact@v3
        with:
          name: NegativityFabric-1.19.2
          path: fabric192/build/libs/NegativityFabric-19.2-1.0.0.jar